spring:
  application:
    name: all-web
server:
  port: 3300

dubbo:
  application:
    name: all-web
  registry:
    address: zookeeper://localhost:2181
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:3301/eureka/

logging:
  config: classpath:log4j.yml