spring:
  application:
    name: cloud-service
server:
  port: 3302

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:3301/eureka/

logging:
  config: classpath:log4j.yml